name: 'Continuous Integration Test'

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality-test:
    name: 'CI: Check quality test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check typescript
        run: yarn type:check

      - name: Check eslint
        run: yarn lint
